version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    groups:
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      changesets:
        patterns:
          - "@changesets/*"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
